Repository GoogleCloudPlatform/market-data-transcoder, pull requests merged in 2023-03, with the labels that each got.

#106 Update README.md
  README.md
  bin/txcode
  examples/README.md
  setup.cfg
Labels: bug, documentation, cleanup

#107 Update examples to use `txcode` from `pip install`
  examples/bin/fix.sh
  examples/bin/pcap.sh
  examples/bin/secdef.sh
Labels: documentation

#108 Changing default output directory
  third_party/sbedecoder/message.py
  transcoder/message/ErrorWriter.py
  transcoder/output/OutputManager.py
Labels: bug, cleanup

#112 Delete path.bash.inc
  path.bash.inc
Labels: documentation, cleanup

#110 Linting
  setup.py
  third_party/pyfixmsg/parser.py
  transcoder/main.py
  transcoder/message/ErrorWriter.py
  transcoder/message/handler/MessageHandler.py
  transcoder/message/handler/MessageHandlerFloatField.py
  transcoder/message/handler/MessageHandlerIntField.py
  transcoder/message/handler/MessageHandlerStringField.py
  transcoder/output/OutputManager.py
Labels: cleanup

#109 WIP: Rename ITCH factory
  README.md
  third_party/sbedecoder/parser.py
  transcoder/message/factory/ITCHMessageFactory.py
  transcoder/message/factory/MessageFactory.py
  transcoder/message/factory/__init__.py
Labels: documentation, cleanup

#117 Setup tools linting clean up
  .github/workflows/pylint.yml
  .pylintrc
  setup.py
  transcoder/__init__.py
  transcoder/main.py
  transcoder/message/factory/ITCHMessageFactory.py
Labels: enhancement, cleanup

#122 Clean up from PR #46
  transcoder/message/ErrorWriter.py
  transcoder/message/MessageParser.py
Labels: cleanup
